---
title: "Exam 1 - Part 1's Solution"
format: 
  html:
    toc: true
editor: visual
---

#### Problem 1. 

Given a simulated dataset below. The tuition is in thousands. 

| Year (since 2000) | Tuition (y) |
|------|---------|
| 0 | 10         |
| 1 |  12       |
| 2 |  14       |
| 3 |  16     |
| 4 |  18       |


1. Calculate the differences  of tuition in consecutive years and ratio of tuition for consecutive years to determine if the data is exponential or linear.

2. Write the equation of the model. 

3. Use the model to predict the tuition in 2030.

4. What year the tuition will be more than 1 million (1000k)?


#### Solution

1. We have the following table.  For a tuition difference, subtract the tuition of a year to the tuition of the previous year (for example: 12.5-10 = 2.5).  For a tuition ratio, divide the tuition of a year to the tuition of the previous year (for example: 12.5/10 = 1.25)

| Year (since 2020) | Tuition | Tuition Difference | Tuition Ratio |
|------|---------|--------------------|---------------|
| 0 | 10      |                    |               |
| 1 | 12    | 2                | 1.2        |
| 2 | 14      | 2                | 1.167      |
| 3 | 16    | 2                | 1.142857      |
| 4 | 18      | 2                | 1.125      |

We observe that the tuition difference is a constant, hence the data is linear. 

2. Let the equation be

$$y = mx +b.$$
Where $y$ and $x$ are the tuition and year, respectively. 

We need to find the constant $m$ and $b$. The slope $m$ is always the different constant, so $m = 2$. 

To find $b$, plug in a data point, say, $x = 0$ and $y = 10$, we have:

$$10 = b$$
Thus, $$b = 10.$$ 

Therefore, the equation is:

$$y = 2*x + 10.$$

3. To predict the tuition in 2030, plug $x = 2030-2000 = 30$ (since 2030 is 30 years since 2000) into the equation in 2. to find $y$. 

$$y =  2*30 + 10 = 70.$$

The model predicts the tuition in 2030 to be 70k.


4. To find the year the tuition passes 1000k, plug $y = 1000$ into the equation to find $x$

We have $$1000 = 2*x + 10$$

Thus, $$x =  \frac{1000-10}{2} = 495$$

Therefore the tuition will pass 100k in the year of 2000 + 495 = 2495. 

#### Problem 2. 

Given a simulated dataset below. The tuition is in thousands.

| Year (since 2000) | Tuition |
|------|---------|
| 0 | 15      |
| 1 | 18.75      |
| 2 | 23.4375|
| 3 | 29.296875   |
| 4 | 36.62109375  |


1. Calculate the differences  of tuition in consecutive years and ratio of tuition for consecutive years to determine if the data is exponential or linear.

2. Write the equation of the model. 

3. Use the model to predict the tuition in 2030.

4. What year the tuition will be more than 1 million (1000k)?

#### Solution

1. We have the following table. 

| Year | Tuition | Tuition Difference | Tuition Ratio |
|------|---------|--------------------|---------------|
| 0 | 15     |                    |               |
| 1 | 18.75      | 3.75                  | 1.25           |
| 2 | 23.4375    | 4.6875                | 1.25           |
| 3 | 29.296875   | 5.859375               | 1.25           |
| 4 | 36.62109375  | 7.324219              | 1.25           |

We observe that the tuition ratio is a constant, hence the data is exponential.  

2. Let the equation be

$$y = a.b^x$$
Where $y$ and $x$ are the tuition and year, respectively. 

We need to find the constant $a$ and $b$. The base $m$ is always the different ratio, so $b = 1.25$.

To find $a$, plug in a data point, say, $x = 0$ and $y = 15$, we have:

$$10 = a*1.25^{0}$$
Thus, $$a = 15$$ 

Therefore, the equation is:

$$y = 15*1.25^x$$

3. To predict the tuition in 2030, plug $x = 2030-2000 = 30$ into the equation in 2. to find $y$. 

$$y =  15*1.25^{30} = 12116.9$$

The model predicts the tuition in 2030 to be 12116.9.


4. To find the year the tuition passes 1000k, plug $y = 1000$ into the equation to find $x$

We have $$1000 = 15*1.25^x$$

Thus, $1.25^ x =  1000/15 = 66.67$.

$$x = \log_{1.25}66.67 = 18.82087 \approx 19$$

Therefore the tuition will pass 1000k in 19 years since 2000, which is 2019. 








