---
title: "MATH 110C. Mathematical Analysis"
format: 
  html:
    toc: true
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

[Syllabus](../syllabus.html)

| Date | Section/Topic | Lecture | 
|------------------|------------------|------------------|
| **Week 1** |  |  |  |
| 1/28 | Basic Functions: Linear Functions | [Note](notes/note1.pdf) | 
| 1/30       | Application of Linear Functions              |    [Note](notes/note2.pdf)   |    
| **Week 2** |  |  |  |
| 2/4       | Modeling with Linear Functions              |    [Note](notes/note3.pdf)   |   
| 2/6       | Excel: Modeling with Linear Functions              |    [Lecture Video](https://bryant.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d08c6b7b-e10d-43ea-a96c-b27c014ed5bc)   |   
| **Week 3** |  |  |  |
| 2/11       | Modeling with Linear Functions              |    [Lecture Video](https://bryant.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=886be002-5e77-4643-b811-b281015b4d23)   |     
| 2/13       | Modeling with Linear Functions              |    [Lecture Video](https://bryant.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=886be002-5e77-4643-b811-b281015b4d23)   |     
| **Week 4** |  |  |  |
| 2/18       | Exponential Functions              |    [Lecture Video](https://bryant.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=89c6783d-a9d0-4c1c-b7da-b288009a54d0), [Note](notes/note4.pdf)   |          
| 2/20       | Simple vs. Compound Interest              |    [Lecture Video](https://bryant.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=3ee4ec35-e73b-4637-900f-b28a0153f6a8), [Note](notes/note5.pdf)   |    
| **Week 5** |  |  |  |
| 2/25 | Logarithms | [Note](notes/note6.pdf) | 
| 2/27 | Logarithms | [Note](notes/note7.pdf) | 
| **Week 6** |  |  |  |
| 3/4 | Exponential Model | [Note](notes/note8.pdf) | 
| 3/6 | Exponential Model | [Lecture Video](https://bryant.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=30b15878-dd8e-4ad1-adba-b298016d7d8b) | 
| **Week 7** | SPRING BREAK |  |  |
| **Week 8** |  |  |  |
| 3/18 | Review for Exam 1 | [Study Guide](exam1_study_guide.html), [Practice 2](exam1_study_guide2.html), [Practice 2's Solution](exam1_study_guide2_solution.html) | 
| 3/20 | Exam 1 |  | 
| **Week 9** |  |  |  |
| 3/25 | Derivatives - Basic Rules | [Note](notes/note9.pdf) | 
| 3/27 | Derivatives | [Note](notes/note10.pdf) | 
| **Week 10** |  |  |  |
| 4/1 | Derivatives | [Note](notes/note11.pdf) | 
| 4/3 | Derivatives  | [Note](notes/note12.pdf) | 
| **Week 10** |  |  |  |
| 4/8 | Derivatives | [Note](notes/note13.pdf) | 
| 4/10 | Derivatives  | [Note](notes/note14.pdf) | 
| **Week 11** |  |  |  |
| 4/8 | Derivatives | [Note](notes/note13.pdf) | 
| 4/10 | Application of Derivatives  | [Note](notes/note14.pdf) | 
| **Week 12** |  |  |  |
| 4/15 | Application of Derivatives | [Note](application_derivatives.html) | 
| 4/17 | Exam 2's Review  | [Practice 1](https://bryantstats.github.io/math110/exams/exam2_practice_problems.html), [Practice 2](https://bryantstats.github.io/math110/exams/exam2_practice_problems2.html), <br> [Solution 1](https://bryantstats.github.io/math110/exams/exam2_practice_problems_solution.html), [Solution 2](https://bryantstats.github.io/math110/exams/exam2_practice_problems2_solution.html)  | 
| **Week 13** |  |  |  |
| 4/22 | Exam 2 |  | 
| 4/24 |  |  | 
| **Week 14** |  |  |  |
| 4/29 | Linear Programming | [Lecture Video](https://bryant.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5f48092f-9fce-40df-b1d2-b2ce013e2e3a)  | 
| 4/30 | Review for Final Exam  | [Practice 1](https://bryantstats.github.io/math110/exams/final_exam_practice1.html), [Solution](https://bryantstats.github.io/math110/exams/final_exam_practice1_solution.html) <br>  [Practice 2](https://bryantstats.github.io/math110/exams/final_exam_practice2.html), [Solution](https://bryantstats.github.io/math110/exams/final_exam_practice2_solution.html) | 
: {.striped .hover}
