---
title: "Exam 1"
format: 
  pdf:
    toc: false
editor: visual
---

Name:________________________________

*The exam will consist of two parts: Part 1: Manual calculation and Part 2: Excel calculation. Submit your answers for Part 1 to receive the problem for Part 2. *

## Part 1: Manual calculation

#### Problem 1. 

Given a simulated dataset below. The tuition is in thousands. 

| Year (since 2000) | Tuition (y) |
|------|---------|
| 0 | 10         |
| 1 |  12       |
| 2 |  14       |
| 3 |  16     |
| 4 |  18       |


1. Calculate the differences  of tuition in consecutive years and ratio of tuition for consecutive years to determine if the data is exponential or linear.

2. Write the equation of the model. 

3. Use the model to predict the tuition in 2030.

4. What year the tuition will be more than 1 million (1000k)?


#### Problem 2. 

Given a simulated dataset below. The tuition is in thousands.

| Year (since 2000) | Tuition |
|------|---------|
| 0 | 15      |
| 1 | 18.75      |
| 2 | 23.4375|
| 3 | 29.296875   |
| 4 | 36.62109375  |


1. Calculate the differences  of tuition in consecutive years and ratio of tuition for consecutive years to determine if the data is exponential or linear.

2. Write the equation of the model. 

3. Use the model to predict the tuition in 2030.

4. What year the tuition will be more than 1 million (1000k)?






